### PR TITLE
Add Backend UI for Entry, Language

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by bitboxer** [comment]
Slowly getting there...

**Comment by EinLama** [comment]
The backend for `/entry` is empty. Based on the name, was this branch expected to include templates for entries? 🤔

**Comment by bitboxer** [comment]
Yes, this is not done. I tagged this as "in-progress" and will continue to work on it next week. Just wanted to have a pr to show the current design 👍

**Comment by bitboxer** [comment]
Okay, now I have a fully working backend with entries, videos and user editing. Now I will add all the tests and then this part of the app is done 👍

**Pull request merged**
