### PR TITLE
User login

### LINKED ISSUE #2: Add basic authentication
This should use guardian and have the following feature set:

- [X] login / logout
- [X] save user in session
- [X] register
- [x] forgot password

### PR DESCRIPTION
**Pull request by bitboxer**
This belongs to #2 

Currently needs to be done:

- [x] tests for `auth_handler`, `session_controller`, `user_controller`
- [x] integration test for user register/login flow, see #5 for details
- [x] i18n support in every view

### CODE REVIEW

**Comment by bitboxer** [comment]
@EinLama this is now reviewable. There is one TODO left in the integration test. I am waiting for help on this one. But besides that everything should work (tm)

**Comment by EinLama** [comment]
Looks good! One note on `config/text.exs`: The `bcrypt_log_rounds` has a minimum value of `4`, as opposed to the `1` we have currently set for tests.

See here: https://hexdocs.pm/comeonin/Comeonin.Bcrypt.html#gen_salt/2

**Comment by bitboxer** [comment]
You are right. Will update to 4 and then merge this

**Comment by EinLama** [comment]
:shipit:

**Pull request merged**
