### PR TITLE
Add graphql API endpoints

### PR DESCRIPTION
**Pull request by jann**

### CODE REVIEW

**Comment by bitboxer** [comment]
This looks really great. Thanks for the huge amount of work ❤️ . Is this done and can be merged?

**Comment by jann** [comment]
Sure, this can be merged. Is there a staging env where we can try it out one last time before deploying it? I only tested it locally...

**Comment by bitboxer** [comment]
Thanks for merging this. Sadly there is no staging, but I will test it tomorrow and release it to production if it works on my machine. I have the full database dump here to check everything 👍

**Comment by bitboxer** [comment]
I just tried to run it localy. The link `http://localhost:4000/graphql-api/graphiql` on the start page shows an error : `no supported media type in accept header, expected one of ["json"]` . Is this how it suppose to work? I expected a HTML page there that makes it easy to explore the api?

**Comment by bitboxer** [comment]
But the endpoint is a working graphql endpoint 👍 . My GraphQL explorer returns valid data with it.

**Comment by bitboxer** [comment]
We could add a page in this wiki here and link to it from the API link and explain everything here. What do you think about that?

**Comment by jann** [comment]
I just tried that URL locally on my machine and it seems to work. But if I follow the API link in the footer it does not, which is very strange. My first guess is some turbolinks magic, but not sure. I can investigate that tomorrow. Anyway writing something up in the wiki sounds good.

**Comment by bitboxer** [comment]
Ah, yes, that could be it! Maybe I have time later tonight to fix it. There is a magic attribute to disable the turbolinks on a link.

**Pull request merged**
