### PR TITLE
Add video model

### PR DESCRIPTION
**Pull request by EinLama**
Bare implementation of the video module. Generated along with views via `mix phoenix.gen.html`

Added later: validation for the states, as defined in #10 

Missing: references to other models. State-traversal, and so on.

### CODE REVIEW

**Comment by bitboxer** [comment]
Looks good so far. One question: since the editing of videos directly is a admin feature later on, do we want to move this to another namespace right now to prepare this?

The user video edit stuff will be done a bit more user friendly with a js app or something I think.

Ah and I searched for state machines in elixir and only found [this](https://github.com/leogi/state_mc). Maybe it is a good fit for the states in the video model?

**Comment by EinLama** [comment]
I have placed the video backend under the `/backend` path for now.

**Comment by EinLama** [comment]
Also moved the controller and the corresponding view/templates to another name. I have not yet figured out how to introduce real namespaces. Instead of `SignDict.VideoController -> SignDict.VideoBackendController`, another option would be `SignDict.Backend.VideoController`. Does anyone know how to implement this?

**Comment by bitboxer** [comment]
Details about how scoped routings work can be found [in the documentation](http://www.phoenixframework.org/docs/routing#section-scoped-routes) . A `SignDict.Backend.VideoController` would be awesome I think.

**Comment by EinLama** [comment]
Thank you for the link! I have moved the controller to `SignDict.Backend.VideoController` 🎊

**Comment by bitboxer** [comment]
Awesome! Do you want to tackle the state traversal in another ticket or do you want to work on it in this pr, too?

**Comment by EinLama** [comment]
I'd like to split this up into another ticket. This is only the base model without any further business logic.

**Comment by EinLama** [comment]
I'd like to refactor the test a bit before merging. Only a small code improvement.

**Pull request merged**
