### PR TITLE
 Add /latest route for displaying recent uploads 

### PR DESCRIPTION
**Pull request by gulp21**

### CODE REVIEW

**Comment by bitboxer** [comment]
Looks really nice. Extra bonus points for "sloth" as example 👍

**Comment by bitboxer** [comment]
@gulp21 it is deployed now, but somehow not sorting correctly. Can you have a look?

**Comment by gulp21** [comment]
> @gulp21 it is deployed now, but somehow not sorting correctly. Can you have a look?

Okay, I guess that `updated_at` is not only changed when updating the video, but also when other events happen (SignWriting update?). I'll have a look later.

**Comment by bitboxer** [comment]
Awesome. Thanks. I think the sign writing update might be it.

**Pull request merged**
